# XcodeGen project specification
# Install XcodeGen: brew install xcodegen
# Then run: xcodegen generate

name: NotToday

options:
  bundleIdPrefix: com.nottoday
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"

settings:
  base:
    PRODUCT_NAME: NotToday
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"

targets:
  NotToday:
    type: application
    platform: macOS
    sources:
      - path: NotToday/Sources/NotToday
        type: group
    settings:
      base:
        INFOPLIST_FILE: NotToday/Sources/NotToday/Info.plist
        CODE_SIGN_STYLE: Automatic
        PRODUCT_BUNDLE_IDENTIFIER: com.nottoday.app
        COMBINE_HIDPI_IMAGES: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/../Frameworks"
    info:
      path: NotToday/Sources/NotToday/Info.plist
      properties:
        CFBundleName: NotToday
        CFBundleDisplayName: NotToday
        CFBundleIdentifier: com.nottoday.app
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0.0"
        CFBundlePackageType: APPL
        CFBundleExecutable: NotToday
        LSMinimumSystemVersion: "13.0"
        LSUIElement: true
        NSPrincipalClass: NSApplication
        NSHighResolutionCapable: true
        CFBundleIconFile: AppIcon

schemes:
  NotToday:
    build:
      targets:
        NotToday: all
    run:
      config: Debug
